-- ====================================================================
-- UNI ROUTE PAKISTAN — PRODUCTION DATABASE SECURITY ARCHITECTURE
-- Target System: Supabase (PostgreSQL) + Row Level Security (RLS)
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. OFFICIAL UNIVERSITY & SCHOLARSHIPS REGISTRY (READ-ONLY FOR PUBLIC)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS university_scholarships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_name TEXT NOT NULL,
  location TEXT,
  country TEXT,
  flag TEXT DEFAULT '🏛️',
  scholarship_title TEXT,
  ranking TEXT DEFAULT '#1',
  coverage TEXT DEFAULT 'Full Ride',
  amount_value TEXT,
  tuition_fee TEXT,
  tuition_numeric NUMERIC DEFAULT 0,
  has_full_ride BOOLEAN DEFAULT true,
  has_partial_aid BOOLEAN DEFAULT true,
  has_financial_aid BOOLEAN DEFAULT true,
  financial_aid_type TEXT DEFAULT 'Need-Blind',
  min_gpa TEXT DEFAULT '3.5 / 4.0',
  min_sat TEXT DEFAULT '1400+',
  sat_category TEXT DEFAULT '1400',
  min_ielts TEXT DEFAULT '7.0+',
  ielts_category TEXT DEFAULT '7.0',
  acceptance_rate TEXT DEFAULT '5.0%',
  deadline TEXT DEFAULT 'Jan 15',
  description TEXT,
  degrees_offered TEXT[] DEFAULT ARRAY['Undergraduate', 'Graduate'],
  tags TEXT[] DEFAULT ARRAY['Global', 'Scholarship'],
  logo_text TEXT,
  logo_bg TEXT DEFAULT 'bg-indigo-950 text-white',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for university_scholarships
ALTER TABLE university_scholarships ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone (authenticated or anonymous public user) can view the university scholarship listings
CREATE POLICY "Public Read Access" 
  ON university_scholarships 
  FOR SELECT 
  USING (true);

-- Policy: Direct denials for write, update, and delete actions for public users.
-- Only database administrators/seed roles can modify official university tables.
CREATE POLICY "Deny Unauthenticated Writes" 
  ON university_scholarships 
  FOR INSERT 
  WITH CHECK (false);

CREATE POLICY "Deny Unauthenticated Updates" 
  ON university_scholarships 
  FOR UPDATE 
  USING (false);

CREATE POLICY "Deny Unauthenticated Deletes" 
  ON university_scholarships 
  FOR DELETE 
  USING (false);


-- --------------------------------------------------------------------
-- 2. SECURE ESSAY HUB DRAFTS (ISOLATED PER USER VIA AUTHENTICATED CONTEXT)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS essays (
  id TEXT PRIMARY KEY,                             -- Unique draft ID
  user_id UUID NOT NULL DEFAULT auth.uid(),       -- Strictly mapped to the authenticated user's ID
  title TEXT NOT NULL DEFAULT 'Untitled Essay',
  essay_type TEXT DEFAULT 'Common App Essay',
  prompt TEXT DEFAULT '',
  word_limit INTEGER DEFAULT 650,
  brainstorm_data JSONB DEFAULT '[]'::jsonb,
  draft_text TEXT DEFAULT '',
  current_stage TEXT DEFAULT 'prompt',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for secure student drafts
ALTER TABLE essays ENABLE ROW LEVEL SECURITY;

-- Policy: Users can ONLY see essays that belong to their unique authenticated session context (auth.uid())
CREATE POLICY "Users can select their own essays" 
  ON essays 
  FOR SELECT 
  USING (auth.uid() = user_id);

-- Policy: Users can ONLY insert essays where the user_id matches their own authenticated identity
CREATE POLICY "Users can insert their own essays" 
  ON essays 
  FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can ONLY update essays that belong to their authenticated identity
CREATE POLICY "Users can update their own essays" 
  ON essays 
  FOR UPDATE 
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can ONLY delete essays that belong to their authenticated identity
CREATE POLICY "Users can delete their own essays" 
  ON essays 
  FOR DELETE 
  USING (auth.uid() = user_id);


-- --------------------------------------------------------------------
-- 3. SECURE ROLE-BASED ACCESS CONTROL (RBAC) TEMPLATE
-- --------------------------------------------------------------------
-- To implement secure admin checks that can never be bypassed on the client,
-- a dedicated 'profiles' table should track roles.
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'Student' CHECK (role IN ('Student', 'Teacher', 'Admin')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own profile
CREATE POLICY "View own profile" 
  ON profiles 
  FOR SELECT 
  USING (auth.uid() = id);

-- Allow only administrators to update roles
CREATE POLICY "Admin full privileges" 
  ON profiles 
  FOR ALL 
  USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND role = 'Admin'
    )
  );
