-- ====================================================================
-- UNI ROUTE — COMPLETE USER DATA & AUTHENTICATION MIGRATION
-- Target System: Supabase (PostgreSQL) + Row Level Security (RLS)
-- Safe, Idempotent, and Non-Destructive (No DROP TABLE, No Data Loss)
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. USER PROFILES TABLE (Linked to auth.users)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'Student' CHECK (role IN ('Student', 'Counselor', 'Teacher', 'Admin')),
  preferences JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Safe column additions in case table already existed
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'Student';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS preferences JSONB DEFAULT '{}'::jsonb;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can view own profile') THEN
    CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can insert own profile') THEN
    CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can update own profile') THEN
    CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
  END IF;
END $$;

-- Automated trigger: Creates a profile record on new Supabase Auth registration
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'Student')
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name),
    updated_at = timezone('utc'::text, now());
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- --------------------------------------------------------------------
-- 2. SAVED / BOOKMARKED UNIVERSITIES (Per User)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.saved_universities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  university_id TEXT NOT NULL,
  university_name TEXT,
  country TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, university_id)
);

CREATE INDEX IF NOT EXISTS idx_saved_unis_user ON public.saved_universities(user_id);

ALTER TABLE public.saved_universities ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'saved_universities' AND policyname = 'Users can select own saved universities') THEN
    CREATE POLICY "Users can select own saved universities" ON public.saved_universities FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'saved_universities' AND policyname = 'Users can insert own saved universities') THEN
    CREATE POLICY "Users can insert own saved universities" ON public.saved_universities FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'saved_universities' AND policyname = 'Users can delete own saved universities') THEN
    CREATE POLICY "Users can delete own saved universities" ON public.saved_universities FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 3. SAT PRACTICE PROGRESS & SECTION ANSWERS (Per User)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sat_practice_progress (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  reading_answers JSONB DEFAULT '{}'::jsonb,
  writing_answers JSONB DEFAULT '{}'::jsonb,
  math_answers JSONB DEFAULT '{}'::jsonb,
  calculator_state JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.sat_practice_progress ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_practice_progress' AND policyname = 'Users can select own SAT progress') THEN
    CREATE POLICY "Users can select own SAT progress" ON public.sat_practice_progress FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_practice_progress' AND policyname = 'Users can insert own SAT progress') THEN
    CREATE POLICY "Users can insert own SAT progress" ON public.sat_practice_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_practice_progress' AND policyname = 'Users can update own SAT progress') THEN
    CREATE POLICY "Users can update own SAT progress" ON public.sat_practice_progress FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_practice_progress' AND policyname = 'Users can delete own SAT progress') THEN
    CREATE POLICY "Users can delete own SAT progress" ON public.sat_practice_progress FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 4. SAT DRILL ACTIVE SESSIONS (In-Progress Drills)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sat_drill_sessions (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  drill_id INTEGER NOT NULL,
  session_data JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  PRIMARY KEY (user_id, drill_id)
);

ALTER TABLE public.sat_drill_sessions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_drill_sessions' AND policyname = 'Users can select own drill sessions') THEN
    CREATE POLICY "Users can select own drill sessions" ON public.sat_drill_sessions FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_drill_sessions' AND policyname = 'Users can insert own drill sessions') THEN
    CREATE POLICY "Users can insert own drill sessions" ON public.sat_drill_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_drill_sessions' AND policyname = 'Users can update own drill sessions') THEN
    CREATE POLICY "Users can update own drill sessions" ON public.sat_drill_sessions FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_drill_sessions' AND policyname = 'Users can delete own drill sessions') THEN
    CREATE POLICY "Users can delete own drill sessions" ON public.sat_drill_sessions FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 5. SAT DRILL COMPLETED RESULTS & HISTORY (Per User)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.sat_drill_results (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  drill_id INTEGER NOT NULL,
  drill_title TEXT,
  estimated_total_score INTEGER,
  total_correct INTEGER,
  total_answered INTEGER,
  total_questions INTEGER,
  accuracy_percentage NUMERIC,
  result_data JSONB NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sat_drill_results_user ON public.sat_drill_results(user_id, drill_id);

ALTER TABLE public.sat_drill_results ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_drill_results' AND policyname = 'Users can select own drill results') THEN
    CREATE POLICY "Users can select own drill results" ON public.sat_drill_results FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_drill_results' AND policyname = 'Users can insert own drill results') THEN
    CREATE POLICY "Users can insert own drill results" ON public.sat_drill_results FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sat_drill_results' AND policyname = 'Users can delete own drill results') THEN
    CREATE POLICY "Users can delete own drill results" ON public.sat_drill_results FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 6. ESSAY HUB DRAFTS (Per User Isolated via auth.uid())
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.essays (
  id TEXT PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT 'Untitled Essay',
  essay_type TEXT DEFAULT 'Common App Essay',
  prompt TEXT DEFAULT '',
  word_limit INTEGER DEFAULT 650,
  brainstorm_data JSONB DEFAULT '[]'::jsonb,
  draft_text TEXT DEFAULT '',
  current_stage TEXT DEFAULT 'prompt',
  progress_percent INTEGER DEFAULT 0,
  last_analysis JSONB DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Safe column additions in case essays already existed
ALTER TABLE public.essays ADD COLUMN IF NOT EXISTS user_id UUID DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.essays ADD COLUMN IF NOT EXISTS progress_percent INTEGER DEFAULT 0;
ALTER TABLE public.essays ADD COLUMN IF NOT EXISTS last_analysis JSONB DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_essays_user ON public.essays(user_id);

ALTER TABLE public.essays ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'essays' AND policyname = 'Users can select own essays') THEN
    CREATE POLICY "Users can select own essays" ON public.essays FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'essays' AND policyname = 'Users can insert own essays') THEN
    CREATE POLICY "Users can insert own essays" ON public.essays FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'essays' AND policyname = 'Users can update own essays') THEN
    CREATE POLICY "Users can update own essays" ON public.essays FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'essays' AND policyname = 'Users can delete own essays') THEN
    CREATE POLICY "Users can delete own essays" ON public.essays FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 7. AI PROFILE ANALYSES (Admissions Assessment Results per User)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profile_analyses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  profile_input JSONB NOT NULL,
  analysis_result JSONB NOT NULL,
  rating_score INTEGER,
  overall_rating TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_profile_analyses_user ON public.profile_analyses(user_id);

ALTER TABLE public.profile_analyses ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profile_analyses' AND policyname = 'Users can select own profile analyses') THEN
    CREATE POLICY "Users can select own profile analyses" ON public.profile_analyses FOR SELECT USING (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profile_analyses' AND policyname = 'Users can insert own profile analyses') THEN
    CREATE POLICY "Users can insert own profile analyses" ON public.profile_analyses FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'profile_analyses' AND policyname = 'Users can delete own profile analyses') THEN
    CREATE POLICY "Users can delete own profile analyses" ON public.profile_analyses FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 8. OPTIONAL PUBLIC UNIVERSITY REGISTRY TABLE
-- (Read-only for public; strictly preserves code data fallback)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.university_scholarships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_name TEXT NOT NULL,
  location TEXT,
  country TEXT,
  flag TEXT DEFAULT '🏛️',
  scholarship_title TEXT,
  ranking TEXT DEFAULT '#1',
  coverage TEXT DEFAULT 'Full Ride',
  amount_value TEXT,
  tuition_fee TEXT,
  tuition_numeric NUMERIC DEFAULT 0,
  has_full_ride BOOLEAN DEFAULT true,
  has_partial_aid BOOLEAN DEFAULT true,
  has_financial_aid BOOLEAN DEFAULT true,
  financial_aid_type TEXT DEFAULT 'Need-Blind',
  min_gpa TEXT DEFAULT '3.5 / 4.0',
  min_sat TEXT DEFAULT '1400+',
  sat_category TEXT DEFAULT '1400',
  min_ielts TEXT DEFAULT '7.0+',
  ielts_category TEXT DEFAULT '7.0',
  acceptance_rate TEXT DEFAULT '5.0%',
  deadline TEXT DEFAULT 'Jan 15',
  description TEXT,
  degrees_offered TEXT[] DEFAULT ARRAY['Undergraduate', 'Graduate'],
  tags TEXT[] DEFAULT ARRAY['Global', 'Scholarship'],
  logo_text TEXT,
  logo_bg TEXT DEFAULT 'bg-indigo-950 text-white',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.university_scholarships ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'university_scholarships' AND policyname = 'Public Read Access') THEN
    CREATE POLICY "Public Read Access" ON public.university_scholarships FOR SELECT USING (true);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 9. GOVERNMENT SCHOLARSHIPS REGISTRY TABLE
-- (Read-only for public; contains full detailed tracks)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.government_scholarships (
  id TEXT PRIMARY KEY,
  program_title TEXT NOT NULL,
  sponsor_government TEXT,
  country TEXT NOT NULL,
  flag TEXT DEFAULT '🌍',
  degree_levels TEXT[] DEFAULT ARRAY['Masters'],
  stipend_monthly TEXT,
  airfare_covered BOOLEAN DEFAULT false,
  health_insurance_covered BOOLEAN DEFAULT false,
  tuition_covered BOOLEAN DEFAULT false,
  deadline TEXT,
  bond_requirement TEXT,
  description TEXT,
  key_eligibility TEXT[] DEFAULT ARRAY[]::text[],
  overview_long TEXT,
  funding_type TEXT,
  work_experience_required TEXT,
  age_limit TEXT,
  hec_nomination_required BOOLEAN DEFAULT false,
  embassy_nomination_required BOOLEAN DEFAULT false,
  application_route TEXT,
  official_sources TEXT[] DEFAULT ARRAY[]::text[],
  step_by_step_process TEXT[] DEFAULT ARRAY[]::text[],
  funding_breakdown JSONB DEFAULT '[]'::jsonb,
  restrictions TEXT[] DEFAULT ARRAY[]::text[],
  logo_text TEXT,
  logo_bg TEXT,
  eligible_nationalities TEXT,
  gpa_requirement TEXT,
  ielts_requirement TEXT,
  is_eligible_for_pakistan BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.government_scholarships ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'government_scholarships' AND policyname = 'Public Read Access for Gov Scholarships') THEN
    CREATE POLICY "Public Read Access for Gov Scholarships" ON public.government_scholarships FOR SELECT USING (true);
  END IF;
END $$;


-- --------------------------------------------------------------------
-- 10. SAT READING & WRITING CONTENT TABLES (Public Read Access)
-- When RLS is turned ON, explicit SELECT policies are required
-- so that web app visitors can fetch lessons and exercises.
-- --------------------------------------------------------------------
DO $$
DECLARE
  t text;
  sat_tables text[] := ARRAY[
    'sat_reading_ch1_theory', 'sat_reading_ch1_exercises',
    'sat_reading_ch2_theory', 'sat_reading_ch2_exercises',
    'sat_reading_ch3_theory', 'sat_reading_ch3_exercises',
    'sat_reading_ch4_theory', 'sat_reading_ch4_exercises',
    'sat_reading_ch5_theory', 'sat_reading_ch5_exercises',
    'sat_reading_ch6_theory', 'sat_reading_ch6_exercises',
    'sat_writing_ch1_theory', 'sat_writing_ch1_exercises',
    'sat_writing_ch2_theory', 'sat_writing_ch2_exercises',
    'sat_writing_ch3_theory', 'sat_writing_ch3_exercises',
    'sat_writing_ch4_theory', 'sat_writing_ch4_exercises',
    'sat_writing_ch5_theory', 'sat_writing_ch5_exercises',
    'sat_writing_ch6_theory', 'sat_writing_ch6_exercises',
    'sat_writing_ch7_theory', 'sat_writing_ch7_exercises',
    'international_universities', 'international_university_programs', 'international_university_scholarships',
    'pakistani_universities', 'pakistani_university_programs', 'pakistani_university_scholarships'
  ];
BEGIN
  FOREACH t IN ARRAY sat_tables LOOP
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t) THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
      EXECUTE format('DROP POLICY IF EXISTS "Public Read Access" ON public.%I;', t);
      EXECUTE format('CREATE POLICY "Public Read Access" ON public.%I FOR SELECT TO anon, authenticated USING (true);', t);
    END IF;
  END LOOP;
END $$;

